### ISSUE TITLE
Link to mutation testing report doesn't work

### ISSUE THREAD

**Issue by REslim30** [stryker-mutator/robobar-example#17]
### Steps to reproduce
1. Click `mutation testing report` link at the bottom of the robobar UI
2. Get a 404 error page.

### Further info
Current link is linking to https://stryker-mutator.io/robobar-example/reports/mutation/html/index.html
Should it be https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/robobar-example/master#mutant?

**Comment by nicojs** [comment]
Ah yes. Fixed with [483043e](https://github.com/stryker-mutator/robobar-example/commit/483043e869496e2cc8d2ff402b21101777540e14)
